
spring.application.name=Back-de-a365


#  CONEXION A LA BASE DE DATOS
spring.datasource.url=jdbc:mysql://localhost:3306/impulsa_a365?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#  JPA / HIBERNATE
# none = Hibernate no modifica las tablas (ya existen en la BD)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


#  SERVIDOR
# Cambiar a 8080
server.port=8081



#  JWT
# Clave secreta para firmar los tokens
jwt.secret=7Kx9mP2vQnR4sT6uW8yZ1aB3cD5eF0gH2iJ4kL6mN8oP0qR2sT4uV6wX8yZ1aB3c
# Expiracion:8 horas
jwt.expiration=28800000
